/**/riptide_slam:
  ros__parameters:
  
    landmarks:
      # Name that will be published in TF2
      FRAME_NAME:
        # Landmark ID make sure is unique
        id: 0

        # Pose of Object from Apriltag aka 0,0,0
        pose: { x: 0, y: 0, z: 0, rx: 0, ry: 0, rz: 0 }
        noise: { 0, 0, 0, 0, 0, 0 }   # x y z rx ry rz


    imu:
      - topic: ""
        enable: [ true, true, true, true, # quaternion pos: x y z w
                  true, true, true,       # angular vel: x y z
                  true, true, true ]      # linear acc: x y z


    twist:
      - topic: ""
        enable: [ true, true, true      # linear: x y z
                  true, true, true ]    # angular: x y z


    pose:
      - topic: ""
        enable: [ true, true, true          # Position: x y z
                  true, true, true, true ]  # Quaternion: x y z w